// <auto-generated />
using System;
using ClouderyApi.Modules.Zhuxs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClouderyApi.Migrations.Zhuxs
{
    [DbContext(typeof(ZhuxsContext))]
    partial class ZhuxsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClouderyApi.Modules.Zhuxs.Domain.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sharables")
                        .HasColumnType("json");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ZhuxsApplications");
                });

            modelBuilder.Entity("ClouderyApi.Modules.Zhuxs.Domain.Term", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Files")
                        .HasColumnType("json");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("RecordDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ZhuxsTerms");
                });

            modelBuilder.Entity("ClouderyApi.Modules.Zhuxs.Domain.Whitelist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ZhuxsWhitelists");
                });
#pragma warning restore 612, 618
        }
    }
}
